// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTNYj1Rah3nhyb-66GxFBhktQnkd9Uuo4',
    appId: '1:37281480791:web:f12c35798ce42d47e8e312',
    messagingSenderId: '37281480791',
    projectId: 'com-smart-attendance',
    authDomain: 'com-smart-attendance.firebaseapp.com',
    storageBucket: 'com-smart-attendance.firebasestorage.app',
    measurementId: 'G-YQ9MCM0MR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYEmMjLbibTpb_-MRBWkOGbRxr-bcSYM',
    appId: '1:37281480791:android:a0ae60f5df157999e8e312',
    messagingSenderId: '37281480791',
    projectId: 'com-smart-attendance',
    storageBucket: 'com-smart-attendance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfzQE5T7Fn9zdRHQ-OFyvirdK9uUS3BKI',
    appId: '1:37281480791:ios:37608ef3182e20bee8e312',
    messagingSenderId: '37281480791',
    projectId: 'com-smart-attendance',
    storageBucket: 'com-smart-attendance.firebasestorage.app',
    iosBundleId: 'com.example.smartAttendenceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfzQE5T7Fn9zdRHQ-OFyvirdK9uUS3BKI',
    appId: '1:37281480791:ios:37608ef3182e20bee8e312',
    messagingSenderId: '37281480791',
    projectId: 'com-smart-attendance',
    storageBucket: 'com-smart-attendance.firebasestorage.app',
    iosBundleId: 'com.example.smartAttendenceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTNYj1Rah3nhyb-66GxFBhktQnkd9Uuo4',
    appId: '1:37281480791:web:1dba708e6b9bd8a3e8e312',
    messagingSenderId: '37281480791',
    projectId: 'com-smart-attendance',
    authDomain: 'com-smart-attendance.firebaseapp.com',
    storageBucket: 'com-smart-attendance.firebasestorage.app',
    measurementId: 'G-H6GWTREGL4',
  );
}
